import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { USE_FIXTURES } from "@/lib/api/config";
import { type RunDetail } from "@/lib/api/runs";
import { getRunServer } from "@/lib/api/server-fetchers";
import { listFindingsServer } from "@/lib/api/server-fetchers";
import { repositoryServer } from "@/lib/api/server-fetchers";
import { enginesServer } from "@/lib/api/server-fetchers";
import {
  labelForEngine,
  fileName,
  formatDebt,
  formatDuration,
  pluralize,
  ratingColorVar,
  scoreColorVar,
  severityMeta,
  truncatePath,
} from "@/lib/utils";
import type { Finding, Severity } from "@/lib/types";
import { SeverityGlyph } from "@/components/severity";
import { PrintButton } from "@/components/report/print-button";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const run = USE_FIXTURES ? null : await getRunServer(id);
  if (!run) return { title: "Report" };

  const repository = run.repoId ? await repositoryServer(run.repoId) : null;
  const name = repository?.name ?? "Project";
  const total = countFindings(run);
  const title = `${name} · quality ${run.score ?? "—"}/100`;
  const description = `Quality gate ${run.gate?.status ?? "not evaluated"}. ${pluralize(
    total,
    "finding"
  )}${run.debtMinutes != null ? ` — ${formatDebt(run.debtMinutes)} of remediation` : ""} on ${run.branch}.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: "article",
      // Rendered by /report/[id]/opengraph-image.tsx
      url: `/report/${id}`,
    },
    twitter: { card: "summary_large_image", title, description },
  };
}

const ORDER: Severity[] = ["critical", "high", "medium", "low", "info"];

/**
 * Public report for ONE run. `[id]` is the run id.
 *
 * ── WHY THIS PAGE MATTERED MOST ──
 *
 * Every screen in this app was fixture-driven, but this is the one built to
 * leave the building: it has an OG card for Slack, a print stylesheet for PDF,
 * and a "share" affordance. It rendered `acme/checkout-service`, a score of 34,
 * and a footer reading "Generated by CodeMentor AI · Semgrep, Checkmarx SAST,
 * ESLint, SonarQube and CodeMentor review · 62.4s" — a specific claim about
 * which analyzers had inspected the code, for a repository that does not
 * exist, on a document whose entire purpose is to be forwarded to someone who
 * cannot check it.
 *
 * So: real run, or 404. There is no fixture fallback on this route when the id
 * does not resolve, because a shareable document that invents its contents is
 * not a degraded experience — it is a false record.
 *
 * The engine list in the footer is derived from the findings themselves, which
 * is the only defensible source: an engine appears there if and only if it
 * produced a result in this run.
 */
export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  const run = USE_FIXTURES ? null : await getRunServer(id);
  if (!run) notFound();

  const [findings, repository, engineRoster] = await Promise.all([
    listFindingsServer({ runId: id, limit: 500 }),
    run.repoId ? repositoryServer(run.repoId) : Promise.resolve(null),
    enginesServer(),
  ]);

  const all = findings ?? [];
  const counts = ORDER.map((s) => ({ s, n: all.filter((f) => f.severity === s).length })).filter(
    (c) => c.n > 0
  );
  const offenders = topOffenders(all);

  // ⚠️ NOT derived from `finding.engine`. That field records which tool the RULE
  //    belongs to — the built-in engine tags its own rules `semgrep`,
  //    `gitleaks`, `eslint` and `sonarjs` after the tools that would normally
  //    catch them. Reading it back as provenance produces a footer crediting
  //    four analyzers that never ran, which is the exact false claim this
  //    rewrite exists to remove. The registry knows what actually executed.
  const engines = (engineRoster ?? [])
    .filter((e) => e.status === "active")
    .map((e) => e.displayName);
  const failed = run.gate?.conditions.filter((c) => c.status === "failed").length ?? 0;

  return (
    <div className="min-h-dvh bg-canvas">
      <div className="mx-auto max-w-[820px] px-6 py-8 print:max-w-none print:px-0 print:py-0">
        {/* ---- masthead ---------------------------------------------------- */}
        <header className="flex items-start justify-between gap-4 border-b border-subtle pb-4">
          <div className="min-w-0">
            <p className="text-2xs font-medium uppercase tracking-[0.06em] text-fg-faint">
              CodeMentor AI · analysis report
            </p>
            <h1 className="mt-1 truncate text-xl font-semibold tracking-[-0.014em] text-fg">
              {repository?.name ?? "Disconnected project"}
            </h1>
            <p className="tnum mt-0.5 font-mono text-2xs text-fg-muted">
              {run.branch}
              {run.commitSha && run.commitSha !== "local" ? ` · ${run.commitSha.slice(0, 7)}` : ""} ·
              run {id}
              {run.finishedAt ? ` · ${new Date(run.finishedAt).toISOString().slice(0, 10)}` : ""}
            </p>
          </div>
          <PrintButton />
        </header>

        {/* ---- verdict ------------------------------------------------------
            The first thing on the page is the decision, not the data. */}
        <section className="print-break mt-5 flex flex-wrap items-center gap-x-8 gap-y-4 rounded-lg border border-subtle bg-surface p-5">
          <div className="flex items-baseline gap-2">
            <span
              className="tnum text-3xl font-semibold leading-none tracking-[-0.026em]"
              data-metric
              style={{ color: scoreColorVar(run.score ?? 0) }}
            >
              {run.score ?? "—"}
            </span>
            <span className="text-md text-fg-faint">/100</span>
            {run.rating ? (
              <span
                className="ml-1 flex h-6 w-6 items-center justify-center rounded-sm border text-sm font-medium"
                style={{
                  color: ratingColorVar(run.rating as never),
                  borderColor: "var(--border-strong)",
                }}
                aria-label={`Rating ${run.rating}`}
              >
                {run.rating}
              </span>
            ) : null}
          </div>

          <div className="min-w-0">
            {run.gate ? (
              <>
                <p
                  className="flex items-center gap-1.5 text-sm font-medium"
                  style={{
                    color:
                      run.gate.status === "passed"
                        ? "var(--sev-success-fg)"
                        : "var(--sev-critical-fg)",
                  }}
                >
                  <span aria-hidden>{run.gate.status === "passed" ? "✓" : "✕"}</span> Quality gate{" "}
                  {run.gate.status}
                </p>
                <p className="tnum mt-0.5 text-2xs text-fg-muted">
                  {failed} of {run.gate.conditions.length} conditions not met
                </p>
              </>
            ) : (
              <p className="text-sm text-fg-muted">No quality gate was evaluated.</p>
            )}
          </div>

          <dl className="ml-auto flex gap-6">
            <Stat label="Findings" value={String(all.length)} />
            <Stat
              label="Debt"
              value={run.debtMinutes != null ? formatDebt(run.debtMinutes) : "—"}
            />
            <Stat label="Lines" value={run.loc != null ? run.loc.toLocaleString() : "—"} />
            {/* Coverage and duplication are not measured — see the settings
                screen. A report is the last place to print a number nothing
                produced. */}
            <Stat label="Coverage" value="not measured" />
          </dl>
        </section>

        {/* ---- severity summary --------------------------------------------- */}
        {counts.length > 0 ? (
          <section className="print-break mt-4">
            <h2 className="text-2xs font-medium uppercase tracking-[0.04em] text-fg-faint">
              Findings by severity
            </h2>
            <div className="mt-1.5 flex flex-wrap gap-2">
              {counts.map(({ s, n }) => (
                <div
                  key={s}
                  className="flex items-center gap-2 rounded-md border border-subtle bg-surface px-2.5 py-1.5"
                >
                  <SeverityGlyph severity={s} size={11} />
                  <span className="text-sm text-fg-secondary">{severityMeta[s].label}</span>
                  <span className="tnum text-sm font-medium text-fg" data-metric>
                    {n}
                  </span>
                </div>
              ))}
            </div>
          </section>
        ) : null}

        {/* ---- dimensions ---------------------------------------------------- */}
        {run.dimensions.length > 0 ? (
          <section className="print-break mt-5">
            <h2 className="text-2xs font-medium uppercase tracking-[0.04em] text-fg-faint">
              Sub-dimensions
            </h2>
            <table className="mt-1.5 w-full border-collapse text-sm">
              <thead>
                <tr className="border-b border-subtle text-left">
                  <th className="py-1.5 font-medium text-fg-muted">Dimension</th>
                  <th className="w-12 py-1.5 text-right font-medium text-fg-muted">Rating</th>
                  <th className="w-14 py-1.5 text-right font-medium text-fg-muted">Score</th>
                  <th className="w-14 py-1.5 text-right font-medium text-fg-muted">Δ</th>
                </tr>
              </thead>
              <tbody>
                {run.dimensions.map((d) => (
                  <tr key={d.key} className="border-b border-subtle align-top">
                    <td className="py-2 pr-3">
                      <div className="text-fg">{d.label}</div>
                      <div className="mt-0.5 text-2xs leading-[1.45] text-fg-muted">{d.reason}</div>
                    </td>
                    <td className="py-2 text-right">
                      <span className="font-medium" style={{ color: ratingColorVar(d.rating) }}>
                        {d.rating}
                      </span>
                    </td>
                    <td className="tnum py-2 text-right text-fg">{d.score}</td>
                    <td
                      className="tnum py-2 text-right"
                      style={{ color: d.delta >= 0 ? "var(--sev-success)" : "var(--sev-critical)" }}
                    >
                      {d.delta === 0 ? "±0" : `${d.delta > 0 ? "+" : "−"}${Math.abs(d.delta)}`}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        ) : null}

        {/* ---- findings ------------------------------------------------------ */}
        <section className="mt-5">
          <h2 className="text-2xs font-medium uppercase tracking-[0.04em] text-fg-faint">
            All findings
          </h2>
          {all.length === 0 ? (
            <p className="mt-1.5 rounded-lg border border-subtle bg-surface px-3 py-3 text-2xs text-fg-muted">
              This run produced no findings.
            </p>
          ) : (
            <ol className="mt-1.5 divide-y divide-[var(--border-subtle)] rounded-lg border border-subtle bg-surface">
              {[...all]
                .sort((a, b) => severityMeta[a.severity].rank - severityMeta[b.severity].rank)
                .map((f) => (
                  <li key={f.id} className="print-break px-3 py-2.5">
                    <div className="flex items-start gap-2.5">
                      <span className="mt-[3px]">
                        <SeverityGlyph severity={f.severity} size={11} />
                      </span>
                      <div className="min-w-0 flex-1">
                        <p className="text-sm leading-[1.45] text-fg">{f.title}</p>
                        <p className="tnum mt-0.5 font-mono text-2xs text-fg-muted">
                          {severityMeta[f.severity].label} · {f.file}:{f.line} · {f.ruleKey}
                          {f.cwe ? ` · ${f.cwe.id}` : ""} · {labelForEngine(f.engine)} ·{" "}
                          {f.confidence}%
                        </p>
                        <p className="mt-1 text-2xs leading-[1.5] text-fg-secondary">
                          {f.whatsWrong}
                        </p>
                      </div>
                      <span className="tnum shrink-0 text-2xs text-fg-faint">
                        {formatDebt(f.effortMinutes)}
                      </span>
                    </div>
                  </li>
                ))}
            </ol>
          )}
        </section>

        {/* ---- offenders ------------------------------------------------------ */}
        {offenders.length > 0 ? (
          <section className="print-break mt-5">
            <h2 className="text-2xs font-medium uppercase tracking-[0.04em] text-fg-faint">
              Highest remediation cost
            </h2>
            <ul className="mt-1.5 divide-y divide-[var(--border-subtle)] rounded-lg border border-subtle bg-surface">
              {offenders.map((f) => (
                <li key={f.path} className="flex items-center gap-3 px-3 py-2">
                  <div className="min-w-0 flex-1">
                    <p className="truncate font-mono text-2xs text-fg">{fileName(f.path)}</p>
                    <p className="truncate font-mono text-2xs text-fg-faint">
                      {truncatePath(f.path, 4)}
                    </p>
                  </div>
                  <span className="tnum shrink-0 text-2xs text-fg-muted">
                    {pluralize(f.findings, "finding")} · {formatDebt(f.debt)}
                  </span>
                </li>
              ))}
            </ul>
          </section>
        ) : null}

        <footer className="mt-6 flex flex-wrap items-center justify-between gap-2 border-t border-subtle pt-3">
          <p className="text-2xs text-fg-faint">
            Generated by CodeMentor AI
            {engines.length > 0 ? ` · ${engines.join(", ")}` : ""}
            {run.durationMs != null ? ` · ${formatDuration(run.durationMs)}` : ""}
          </p>
          <Link
            href={run.repoId ? `/reviews?repo=${encodeURIComponent(run.repoId)}` : "/reviews"}
            className="text-2xs text-fg-secondary underline-offset-2 hover:underline no-print"
          >
            Open in CodeMentor →
          </Link>
        </footer>
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-2xs text-fg-faint">{label}</dt>
      <dd className="tnum text-md font-medium text-fg" data-metric>
        {value}
      </dd>
    </div>
  );
}

function countFindings(run: RunDetail): number {
  return Object.values(run.findingCounts ?? {}).reduce((a, b) => a + b, 0);
}

/** Grouped from this run's own findings — not the repository's latest. */
function topOffenders(findings: Finding[]) {
  const byFile = new Map<string, { path: string; findings: number; debt: number }>();
  for (const f of findings) {
    const row = byFile.get(f.file) ?? { path: f.file, findings: 0, debt: 0 };
    row.findings += 1;
    row.debt += f.effortMinutes;
    byFile.set(f.file, row);
  }
  return [...byFile.values()].sort((a, b) => b.debt - a.debt).slice(0, 5);
}
